contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #{{ short_name }} channel"
    url: https://nfcore.slack.com/channels/{{ short_name }}
    about: Discussion about the {{ name }} pipeline
